version: '3'

services:
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql_data:/bitnami/postgresql/data
    env_file:
      - .env
